#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-curb
Version  : 0.8.8
Release  : 9
URL      : https://rubygems.org/downloads/curb-0.8.8.gem
Source0  : https://rubygems.org/downloads/curb-0.8.8.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Ruby
Requires: rubygem-curb-lib
BuildRequires : curl-dev
BuildRequires : libidn-dev
BuildRequires : openssl-dev
BuildRequires : ruby
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit
BuildRequires : zlib-dev

%description
# Curb - Libcurl bindings for Ruby
* [rubyforge rdoc](http://curb.rubyforge.org/)
* [rubyforge project](http://rubyforge.org/projects/curb)
* [github project](http://github.com/taf2/curb/tree/master)

%package lib
Summary: lib components for the rubygem-curb package.
Group: Libraries

%description lib
lib components for the rubygem-curb package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n curb-0.8.8
gem spec %{SOURCE0} -l --ruby > rubygem-curb.gemspec

%build
gem build rubygem-curb.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
curb-0.8.8.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/curb-0.8.8 && rake --trace test TESTOPTS="-v" || : && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/curb-0.8.8.gem
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/curb-0.8.8/gem.build_complete
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/curb-0.8.8/gem_make.out
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/curb-0.8.8/mkmf.log
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/README.markdown
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/doc.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/.RUBYARCHDIR.time
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/Makefile
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/curb.c
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/curb.h
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/curb.o
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/curb_config.h
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/curb_easy.c
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/curb_easy.h
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/curb_easy.o
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/curb_errors.c
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/curb_errors.h
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/curb_errors.o
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/curb_macros.h
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/curb_multi.c
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/curb_multi.h
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/curb_multi.o
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/curb_postfield.c
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/curb_postfield.h
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/curb_postfield.o
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/curb_upload.c
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/curb_upload.h
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/curb_upload.o
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/extconf.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/lib/curb.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/lib/curl.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/lib/curl/easy.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/lib/curl/multi.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/alltests.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/bug_crash_on_debug.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/bug_crash_on_progress.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/bug_curb_easy_blocks_ruby_threads.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/bug_curb_easy_post_with_string_no_content_length_header.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/bug_instance_post_differs_from_class_post.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/bug_issue102.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/bug_multi_segfault.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/bug_postfields_crash.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/bug_postfields_crash2.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/bug_require_last_or_segfault.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/bugtests.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/mem_check.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/require_last_or_segfault_script.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/signals.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/tc_curl.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/tc_curl_download.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/tc_curl_easy.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/tc_curl_easy_setopt.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/tc_curl_multi.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/tc_curl_postfield.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/timeout.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/timeout_server.rb
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/tests/unittests.rb
/usr/lib64/ruby/gems/2.3.0/specifications/curb-0.8.8.gemspec

%files lib
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/curb-0.8.8/curb_core.so
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/ext/curb_core.so
/usr/lib64/ruby/gems/2.3.0/gems/curb-0.8.8/lib/curb_core.so
